### PR TITLE
User-Defined Javascript Libraries

### PR DESCRIPTION
**Pull request by jayeheffernan**
This pull request adds support for users to provide their own Javascript files to add custom functions to be used by Builder directives.  This could be used, for example, to include math or string-manipulation libraries in Builder's namespace, or to define your own preprocessing functions to run on files that are `@include`d.

Node.js files typically set a `module.exports` value, usually to an object, which contains the values that the library exports.  When including these files with Builder, the `module.exports` object is merged into Builder's internal "global" namespace.  Files can be specified for including using paths to files or directories, or with globs.  See the readme for more.

Tests and an update to the documentation are included.  Please note the following limitation, from the readme:

> Due to the way nested property names are resolved, Javascript functions and methods may be called with a `this` value that is different to what you expect.  Take the following example library:
> 
> ```js
> class MyClass {
>   constructor(str) {
>     this._str = str;
>   }
> 
>   getStr() {
>     return this._str;
>   }
> }
> 
> myObject = MyClass("my text");
> 
> module.exports = {
>   myObject
> };
> ```
> Attempting to use this library with the directive `@{myObject.getStr()}` will fail due to `this` being undefined on line 7 of the Javascript file.  It is recommended not to try to call Javascript methods in your Builder input files, and to write your Javascript files such that they only export functions which can be called as "stand-alone" functions which don't depend on being called with any particular `this` value.

### CODE REVIEW

**Comment by deldrid1** [comment]
@jayeheffernan - it looks like it works from a documentation perspective, but in practice it isn't working quite right for me..

I've run the following command to get your version
```
$ npm install git://github.com/jayeheffernan/Builder#user-filters
```

I use gulp to actually run builder and I create my instance of builder like this:
```javascript
var builder = new Builder({ libs: ["gulp-tasks/lib/builderJSExtensions"] })
```

`gulp-tasks/lib/builderJSExtensions` contains a `str.js`, whose contents are below:
```javascript
module.exports = {
  upperCase: function(s) {
      console.log(s)
      s[0] = s[0].toUpperCase()
      return "TEST" //Not sure what's going on here, but this isn't working at all...
  },
  repeat: (s) => s[0].repeat(s[1]),
  split: (s) => s[0].split(s[1])[s[2]],
  length: (s) => s[0].length
};

// Why are areguments being presented as an array instead of as discrete arguments
// module.exports = {
//     upper: (s) => s.toUpperCase(),
//     repeat: (s, count) => s.repeat(count),
//     split: (s, seperator, index) => s.split(seperator)[index],
//     length: (s) => s.length
//   };
```

Finally, I have an `agent.nut` whose contents are: 
```squirrel
@macro HEADER(file)
// @set file upperCase(split(file, ".", 0))
@set file upperCase(file)
// =============================================================================
// @{file} @{repeat("-", 76 - length(file))}
// ============================================================================{

@endmacro

@macro FOOTER(file)
@set filename split(file, ".", 0)
@set file upperCase(filename)

@{filename}
@{file}

// =============================================================================
// @{repeat("-", 72 - length(file))} END_@{file}
// ============================================================================}
@endmacro


@{HEADER(__FILE__)}
// Test my stuff!
@{FOOTER(__FILE__)}
```

and who becomes the following after running builder:
```squirrel
// @set file upperCase(split(file, ".", 0))
// =============================================================================
// agent.nut -------------------------------------------------------------------
// ============================================================================{

// Test my stuff!

agent
agent.nut

// =============================================================================
// --------------------------------------------------------------- END_agent.nut
// ============================================================================}
```

I've not had a ton of time to devote to this, but my issues so far are these:
 - my `upperCase()` function is being called (as evidenced from the console.log()) but it isn't working and I have no idea why?
- the module.exports functions aren't being called the way your doucmentation describes.  They are called with a single array of arguments instead of being called with the arguments directly

Once these couple of minor things are addressed, I think this will be a VERY useful PR!

**Comment by jayeheffernan** [comment]
Thanks for the feedback @deldrid1! The calling-with-array problem is familiar to me. I think I might have fixed it for nested functions but not those at the top level.  The other issue I'll have to figure out when I'm at a computer.  I'll try to take a look at both over the next couple of days and let you know when they're fixed.

It makes sense to me to have some basic string functions like toUppercase, split, slice, repeat, substitute included by default. What do you think of that?

**Comment by deldrid1** [comment]
@jayeheffernan thanks for the updates.

I think having basic string manipulation included by default makes perfect sense!

Also, I'm still having some issues...  It seems like if you have multiple function calls inside of a macro, only the innermost function call is being returned?  My upperCase function above is still not returning "TEST" like it should be...

Oddly, if I pull stuff out of the macro it looks like it works okay?

**Comment by jayeheffernan** [comment]
I'm still looking in to this.  It seems like there are some issues with using other Builder directives inside of macro bodies, e.g. see https://github.com/electricimp/Builder/issues/19.  There's some work that's for me to do in the scope of this pull request and some that's probably not.  If you get a moment, please include an example of what you mean about the innermost function call.

**Comment by jayeheffernan** [comment]
@deldrid1 I hope I've now fixed all of your issues.  There is a unit test based on your original use case [here](https://github.com/electricimp/Builder/pull/34/files#diff-7611f289adce795ce3adb9a1058fd320).

As part of this I've fixed an issue with the way context is handled which was causing problems like https://github.com/electricimp/Builder/issues/19.

I've also added a few string functions e.g. `concat()`, `repeat()`, `toUpperCase()`, and `trim()`.

@ppetrosh I'm now compatible with Node v4.0.0 again.

**Comment by ppetrosh** [comment]
@jayeheffernan @deldrid1 thanks a lot guys for this effort! This seems to be a very useful extension to the Builder. I'm sorry for the delay.

I tested it on my end and it seems to work fine for me. Merging the branch and will take care of the documentation (will add some more examples, explanations) for the new features.

**Pull request merged**
