### PR TITLE
v2.7.0

### PR DESCRIPTION
**Pull request by FedorUporov**
Add 'reproducible artifacts built from GitHub' feature.

Fixed issues:
- https://github.com/electricimp/Builder/issues/52

### CODE REVIEW

**Comment by betzrhodes** [comment]
Will this update effect impt or other tooling? I'm looking specifically it the tools that grab the latest Builder version, and may be effected by the changes in how Builder needs to be instantiated as a library.

**Comment by FedorUporov** [comment]
The Builder library API was not touched by this update.
So, it is not expected that any tooling, like impt or anything else could be effected.

**Comment by betzrhodes** [comment]
I'd like to get all the tests to pass locally. However I keep getting the following failure:

1) Machine should exhibit the expeted behaviour when including user-defined Javascript libraries
  Message:
    Expected '[Mon Apr 15 2019 15:05:24 GMT-0700 (Pacific Daylight Time)] INFO Including source "input.nut"
    ' to be 'Hello world!
    '.
  Stack:
    Error: Expected '[Mon Apr 15 2019 15:05:24 GMT-0700 (Pacific Daylight Time)] INFO Including source "input.nut"
    ' to be 'Hello world!
    '.
        at stdoutFixture.capture.message (/Volumes/Waystone/ElectricImp/github_repos/Builder/spec/Machine/sample-12-spec.js:26:25)
        at WriteStream.write (/Volumes/Waystone/ElectricImp/github_repos/Builder/node_modules/fixture-stdout/index.js:32:46)

**Comment by betzrhodes** [comment]
Looks good.

**Comment by FedorUporov** [comment]
> I'd like to get all the tests to pass locally. However I keep getting the following failure:
> 
>     1. Machine should exhibit the expeted behaviour when including user-defined Javascript libraries
>        Message:
>        Expected '[Mon Apr 15 2019 15:05:24 GMT-0700 (Pacific Daylight Time)] INFO Including source "input.nut"
>        ' to be 'Hello world!
>        '.
>        Stack:
>        Error: Expected '[Mon Apr 15 2019 15:05:24 GMT-0700 (Pacific Daylight Time)] INFO Including source "input.nut"
>        ' to be 'Hello world!
>        '.
>        at stdoutFixture.capture.message (/Volumes/Waystone/ElectricImp/github_repos/Builder/spec/Machine/sample-12-spec.js:26:25)
>        at WriteStream.write (/Volumes/Waystone/ElectricImp/github_repos/Builder/node_modules/fixture-stdout/index.js:32:46)
> 
> 
> I changed my log level, and this test now passes - This test might want to be updated, so if log level is set to debug or info it still passes.

Could you please provide some additional information about this issue.
Like, which OS (Win or OSX) you use, and how the log level was changed by you.
I want to reproduce it locally.
In all cases the unit-tests should pass on clean repo checkout without any local fixes.
So, I want to investigate this case.

**Comment by betzrhodes** [comment]
I'm on a mac OS 10.14.4. 
To run tests I created a branch in my local Builder repo with the code update in this pull request. Then from that folder/branch I ran `npm install`. In the test directions it lists these variables/instructions: 

SPEC_LOGLEVEL=<debug|info|warning|error> \
SPEC_GITHUB_USERNAME=<GitHub username> \
SPEC_GITHUB_TOKEN=<GitHub password/access token> \
npm test

So I set the SPEC_LOGLEVEL to debug `export SPEC_LOGLEVEL=debug`. 
Then set my github credentials the same way. 
Then ran `npm test`.

Got these logs as the tests started to run, so I believe I was running the tests on the updated version of Builder. 
> Builder@2.7.0 test /Volumes/Waystone/ElectricImp/github_repos/Builder
> jasmine

When I changed `SPEC_LOGLEVEL=warning` all tests passed.

**Comment by FedorUporov** [comment]
> I'm on a mac OS 10.14.4.
> To run tests I created a branch in my local Builder repo with the code update in this pull request. Then from that folder/branch I ran `npm install`. In the test directions it lists these variables/instructions:
> 
> SPEC_LOGLEVEL=<debug|info|warning|error>
> SPEC_GITHUB_USERNAME=
> SPEC_GITHUB_TOKEN=<GitHub password/access token>
> npm test
> 
> So I set the SPEC_LOGLEVEL to debug `export SPEC_LOGLEVEL=debug`.
> Then set my github credentials the same way.
> Then ran `npm test`.
> 
> Got these logs as the tests started to run, so I believe I was running the tests on the updated version of Builder.
> 
> > Builder@2.7.0 test /Volumes/Waystone/ElectricImp/github_repos/Builder
> > jasmine
> 
> When I changed `SPEC_LOGLEVEL=warning` all tests passed.

Ok, thank you for detailed description.
Now I am able to reproduce it locally.
I think it is possible to fix this issue in https://github.com/electricimp/Builder/issues/42 task context.

**Comment by betzrhodes** [comment]
Great then I'll close and release this version. Thanks!

**Pull request merged**
